from __future__ import annotations

import importlib.util
import json
import os
from pathlib import Path
import plistlib
import stat
import subprocess
import sys
from types import SimpleNamespace
from unittest import mock

from tests.control_plane.support import REPO_ROOT, TempDirTestCase, init_git_repo, run_command, write_json, write_text


SPEC = importlib.util.spec_from_file_location("retire_agent_clients", REPO_ROOT / "scripts/retire-agent-clients.py")
assert SPEC and SPEC.loader
RETIRE = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = RETIRE
SPEC.loader.exec_module(RETIRE)


class RetireAgentClientsTests(TempDirTestCase):
    def setUp(self) -> None:
        super().setUp()
        self.home = (self.temp_path / "home").resolve()
        self.github = self.home / "GitHub"
        self.repo = init_git_repo(self.github / "angie")
        self.other = init_git_repo(self.github / "other")
        self.registry = write_json(self.home / "repos.json", {"repos": [
            {"path": "~/GitHub/angie", "model_instructions_file": "../identity.md"},
            {"path": "~/GitHub/other"},
        ]})
        self.entries = [
            {"root": self.repo, "model_instructions_file": "../identity.md"},
            {"root": self.other},
        ]

    def run_retire(self, *args: str, check: bool = True):
        return run_command([
            sys.executable, str(REPO_ROOT / "scripts/retire-agent-clients.py"),
            "--home", str(self.home), "--repo-registry", str(self.registry), *args,
        ], check=check)

    def retirement(self):
        return RETIRE.Retirement(self.home, self.github, self.entries)

    def hook(self, script: str = "claude_stop.py", runtime: str = "") -> dict:
        return {"type": "command", "command": f'python3 "$HOME/GitHub/agents/hooks/scripts/{script}"{runtime}'}

    def link(self, path: Path, target: Path) -> Path:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.symlink_to(os.path.relpath(target, path.parent))
        return path

    def test_dry_run_and_check_do_not_write_or_reveal_config_values(self) -> None:
        target = write_json(self.home / ".copilot/settings.json", {"askUser": False, "token": "KEEP_PRIVATE_TOKEN"})
        before = target.read_bytes()
        dry = self.run_retire()
        self.assertEqual(dry.returncode, 0)
        self.assertIn("UPDATE", dry.stdout)
        self.assertNotIn("KEEP_PRIVATE_TOKEN", dry.stdout + dry.stderr)
        checked = self.run_retire("--check", check=False)
        self.assertEqual(checked.returncode, 1)
        self.assertEqual(target.read_bytes(), before)
        self.assertFalse((self.home / ".local/state").exists())

    def test_repo_cleanup_preserves_codex_identity_workflows_and_real_skills(self) -> None:
        identity = write_text(self.repo / "identity.md", "private identity source\n")
        write_text(self.repo / "AGENTS.md", "router\n")
        write_text(self.repo / ".claude/CLAUDE.md", "@../identity.md\n@../AGENTS.md\n")
        copilot = self.link(self.repo / ".github/copilot-instructions.md", identity)
        write_json(self.repo / ".claude/settings.json", {"autoMemoryEnabled": False, "hooks": {"SessionStart": [{"hooks": [self.hook("session_start.py", " --runtime claude")]}]}})
        write_json(self.repo / ".claude/launch.json", {"version": "0.0.1", "configurations": [{"runtimeExecutable": "pnpm"}]})
        write_text(self.repo / ".github/github-app.yml", "# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY.\n# Source: ~/GitHub/agents/dev-servers/registry.json\nscripts: {}\n")
        workflow = write_text(self.repo / ".github/workflows/ci.yml", "name: Keep\n")
        codex = write_text(self.repo / ".codex/config.toml", "preserve = true\n")
        source = write_text(self.github / "agents/skills-source/owned/example/SKILL.md", "source\n")
        owned = self.link(self.repo / ".claude/skills/example", source.parent)
        local = write_text(self.repo / ".agents/skills/local/SKILL.md", "local source\n")
        mirror = self.link(self.repo / ".claude/skills/local", local.parent)
        real = write_text(self.repo / ".claude/skills/real/SKILL.md", "independent skill\n")
        unknown_source = write_text(self.home / "unmanaged-skill/SKILL.md", "keep\n")
        unknown = self.link(self.repo / ".claude/skills/unknown", unknown_source.parent)
        self.run_retire("--apply")
        for path in (copilot, owned, mirror, self.repo / ".claude/CLAUDE.md", self.repo / ".claude/settings.json", self.repo / ".claude/launch.json", self.repo / ".github/github-app.yml"):
            self.assertFalse(path.exists() or path.is_symlink(), str(path))
        for path in (identity, workflow, codex, source, local, real, unknown, unknown_source):
            self.assertTrue(path.exists(), str(path))
        self.assertEqual(identity.read_text(), "private identity source\n")

    def test_global_overlay_cleanup_keeps_tokens_history_and_unrelated_preferences(self) -> None:
        private = "KEEP_PRIVATE_TOKEN"
        write_json(self.home / ".claude/settings.json", {
            "apiKey": private, "effortLevel": "high", "includeGitInstructions": False,
            "permissions": {"allow": ["Bash", "Read", "Custom"], "deny": ["Danger"], "defaultMode": "bypassPermissions", "additionalDirectories": [str(self.repo), str(self.home / "outside")]},
            "enabledPlugins": {"anthropic-skills@inline": False, "other": True},
            "skillOverrides": {"verify": "off", "my-skill": "on"},
            "sshConfigs": [{"id": "macmini"}, {"id": "other", "sshHost": "keep"}],
            "hooks": {"Stop": [{"matcher": "*", "hooks": [self.hook(), {"command": "keep-custom-hook"}]}]},
        })
        write_json(self.home / ".claude.json", {"oauthAccount": {"token": private}, "autoUpdates": False, "projects": {
            str(self.repo): {"hasTrustDialogAccepted": True, "hasCompletedProjectOnboarding": True, "history": "keep"},
            str(self.home / "outside"): {"hasTrustDialogAccepted": True},
        }})
        write_json(self.home / "Library/Application Support/Claude/config.json", {"chromeExtensionEnabled": False, "windowBounds": {"x": 1}})
        write_json(self.home / ".copilot/settings.json", {"autoUpdate": False, "disabledSkills": ["af", "mine"], "tabs": {"hide": ["issues", "agents"], "custom": True}, "token": private})
        write_text(self.home / ".copilot/config.json", '// managed header\n' + json.dumps({"trustedFolders": [str(self.repo), str(self.github), str(self.home / "outside")], "token": private}))
        history = write_text(self.home / ".copilot/session-state/private/history.jsonl", "private history\n")
        output = self.run_retire("--apply")
        self.assertNotIn(private, output.stdout + output.stderr)
        settings = json.loads((self.home / ".claude/settings.json").read_text())
        self.assertEqual(settings["apiKey"], private)
        self.assertEqual(settings["permissions"], {"allow": ["Custom"], "deny": ["Danger"], "additionalDirectories": [str(self.home / "outside")]})
        self.assertEqual(settings["enabledPlugins"], {"other": True})
        self.assertEqual(settings["skillOverrides"], {"my-skill": "on"})
        self.assertEqual(settings["sshConfigs"], [{"id": "other", "sshHost": "keep"}])
        self.assertEqual(settings["hooks"]["Stop"][0]["hooks"], [{"command": "keep-custom-hook"}])
        state = json.loads((self.home / ".claude.json").read_text())
        self.assertEqual(state["oauthAccount"]["token"], private)
        self.assertEqual(state["projects"][str(self.repo)], {"history": "keep"})
        self.assertIn("hasTrustDialogAccepted", state["projects"][str(self.home / "outside")])
        self.assertEqual(json.loads((self.home / ".copilot/settings.json").read_text()), {"disabledSkills": ["mine"], "tabs": {"hide": ["agents"], "custom": True}, "token": private})
        self.assertEqual(json.loads((self.home / ".copilot/config.json").read_text())["trustedFolders"], [str(self.home / "outside")])
        self.assertEqual(history.read_text(), "private history\n")

    def test_repo_local_permissions_and_regular_bridges_retire_but_credentials_stay(self) -> None:
        local = write_json(self.repo / ".claude/settings.local.json", {"permissions": {"allow": ["Bash(custom:*)"]}})
        mixed = write_json(self.other / ".claude/settings.local.json", {"permissions": {"allow": ["Read"]}, "env": {"TOKEN": "PRIVATE"}, "custom": True})
        bridges = [write_text(self.repo / relative, "retired client instructions\n") for relative in ("CLAUDE.md", ".claude/CLAUDE.md", ".github/copilot-instructions.md")]
        self.run_retire("--apply")
        self.assertFalse(local.exists())
        self.assertEqual(json.loads(mixed.read_text()), {"env": {"TOKEN": "PRIVATE"}, "custom": True})
        for bridge in bridges:
            self.assertFalse(bridge.exists())

    def test_codex_identity_source_in_retired_guidance_location_is_preserved(self) -> None:
        source = write_text(self.other / "CLAUDE.md", "still the Codex identity source\n")
        write_json(self.registry, {"repos": [{"path": "~/GitHub/other", "model_instructions_file": "../CLAUDE.md"}]})
        self.run_retire("--apply")
        self.assertEqual(source.read_text(), "still the Codex identity source\n")
        source.unlink()
        identity = write_text(self.other / "identity.md", "keep identity\n")
        self.link(source, identity)
        self.run_retire("--apply")
        self.assertTrue(source.is_symlink())
        self.assertEqual(source.read_text(), "keep identity\n")

    def test_mcp_pruning_preserves_unknown_and_custom_same_name_servers(self) -> None:
        managed = {"type": "http", "url": "https://developers.openai.com/mcp"}
        unknown = {"url": "https://example.test/mcp", "headers": {"Authorization": "PRIVATE"}}
        custom = {"type": "http", "url": "https://custom.test/mcp"}
        for path in (self.repo / ".mcp.json", self.repo / ".github/mcp.json", self.home / ".copilot/mcp-config.json"):
            write_json(path, {"mcpServers": {"openaiDeveloperDocs": managed, "unknown": unknown, "figma": custom}, "other": True})
        self.run_retire("--apply")
        for path in (self.repo / ".mcp.json", self.repo / ".github/mcp.json", self.home / ".copilot/mcp-config.json"):
            self.assertEqual(json.loads(path.read_text()), {"mcpServers": {"unknown": unknown, "figma": custom}, "other": True})
        write_json(self.repo / ".mcp.json", {"mcpServers": {"openaiDeveloperDocs": managed}})
        write_json(self.home / ".copilot/mcp-config.json", {"mcpServers": {"playwright": {"type": "local", "command": "npx", "args": ["-y", "@playwright/mcp@latest"], "tools": ["*"]}}})
        self.run_retire("--apply")
        self.assertFalse((self.repo / ".mcp.json").exists())
        self.assertFalse((self.home / ".copilot/mcp-config.json").exists())

    def test_generated_global_links_and_wrappers_only(self) -> None:
        source = write_text(self.github / "agents/config/global.agents.md", "keep source\n")
        guidance = [self.link(self.home / path, source) for path in (".claude/CLAUDE.md", ".copilot/copilot-instructions.md", ".gemini/GEMINI.md")]
        generated = write_text(self.home / "bin/claude", '#!/usr/bin/env bash\nset -euo pipefail\nreal_cli="${CLAUDE_REAL_BIN:-$default_real_cli}"\n# claude launcher cannot find executable real CLI:\nexec "$real_cli" --dangerously-skip-permissions "$@"\n')
        custom = write_text(self.home / "bin/copilot", "#!/bin/sh\nexec custom-tool\n")
        actual = write_text(self.home / ".local/bin/agy", "unmanaged executable\n")
        custom_link = self.link(self.home / "bin/agy", actual)
        self.run_retire("--apply")
        for path in (*guidance, generated):
            self.assertFalse(path.exists() or path.is_symlink())
        for path in (source, custom, actual, custom_link):
            self.assertTrue(path.exists())

    def test_antigravity_and_vscode_leave_other_settings_and_history(self) -> None:
        write_json(self.home / ".gemini/antigravity-cli/settings.json", {"toolPermission": "always-proceed", "trustedWorkspaces": [str(self.repo), str(self.home / "outside")], "token": "private"})
        write_json(self.home / ".gemini/config/hooks.json", {"hooks": {"Stop": [{"hooks": [self.hook("antigravity_stop.py"), {"command": "keep"}]}]}})
        write_json(self.home / ".vscode-server/data/User/globalStorage/agent-host-config.json", {"globalAutoApproveEnabled": True, "autoReplyEnabled": False, "terminalAutoApproveEnabled": True, "terminalAutoApproveRules": {"curl": True, "/.*/": True, "keep": False}, "model": "keep"})
        vscode = write_text(self.home / "Library/Application Support/Code/User/settings.json", '''{
          // keep editor values and strings containing comment-like content
          "editor.fontSize": 14,
          "custom.url": "https://example.test/path//value",
          "chat.permissions.default": "autoApprove",
          "chat.defaultConfiguration": {"mode": "autopilot", "approvals": "autoApprove", "custom": true},
          "chat.mcp.discovery.enabled": {"claude-desktop": false, "mine": true},
        }\n''')
        history = write_text(self.home / ".gemini/antigravity-cli/history/private", "keep history")
        self.run_retire("--apply")
        self.assertEqual(json.loads(vscode.read_text()), {"editor.fontSize": 14, "custom.url": "https://example.test/path//value", "chat.defaultConfiguration": {"custom": True}, "chat.mcp.discovery.enabled": {"mine": True}})
        agy = json.loads((self.home / ".gemini/antigravity-cli/settings.json").read_text())
        self.assertEqual(agy, {"trustedWorkspaces": [str(self.home / "outside")], "token": "private"})
        host = json.loads((self.home / ".vscode-server/data/User/globalStorage/agent-host-config.json").read_text())
        self.assertEqual(host, {"terminalAutoApproveRules": {"keep": False}, "model": "keep"})
        self.assertEqual(history.read_text(), "keep history")

    def test_exact_repo_filter_rejects_unknown_and_does_not_touch_other_repo(self) -> None:
        for repo in (self.repo, self.other):
            write_text(repo / ".claude/CLAUDE.md", "@../AGENTS.md\n")
        bad = self.run_retire("--apply", "--repo", str(self.repo / "nested"), check=False)
        self.assertEqual(bad.returncode, 2)
        self.assertTrue((self.repo / ".claude/CLAUDE.md").exists())
        self.run_retire("--apply", "--repo", str(self.repo))
        self.assertFalse((self.repo / ".claude/CLAUDE.md").exists())
        self.assertTrue((self.other / ".claude/CLAUDE.md").exists())

    def test_symlinked_settings_and_directories_are_not_followed(self) -> None:
        source = write_json(self.home / "outside/settings.json", {"askUser": False, "private": True})
        self.link(self.home / ".copilot/settings.json", source)
        outside = write_json(self.home / "external/launch.json", {"private": True})
        self.link(self.repo / ".claude", outside.parent)
        before = source.read_bytes(), outside.read_bytes()
        self.run_retire("--apply")
        self.assertEqual((source.read_bytes(), outside.read_bytes()), before)
        self.assertTrue((self.repo / ".claude").is_symlink())

    def test_backup_is_private_and_second_apply_is_noop(self) -> None:
        target = write_json(self.home / ".copilot/settings.json", {"askUser": False, "token": "private"})
        before = target.read_bytes()
        self.run_retire("--apply")
        base = self.home / ".local/state/agents-control-plane/retired-client-backups"
        backups = list(base.rglob("settings.json"))
        self.assertEqual(len(backups), 1)
        self.assertEqual(backups[0].read_bytes(), before)
        self.assertEqual(stat.S_IMODE(backups[0].stat().st_mode), 0o600)
        self.assertEqual(stat.S_IMODE(base.stat().st_mode), 0o700)
        before_files = sorted(str(path) for path in base.rglob("*"))
        self.assertIn("0 retired-client", self.run_retire("--apply").stdout)
        self.assertEqual(sorted(str(path) for path in base.rglob("*")), before_files)
        self.assertEqual(self.run_retire("--check").returncode, 0)

    def make_job(self, suffix: str, script: str | None = None, label_prefix: str = "com.fixture") -> Path:
        label = f"{label_prefix}.{suffix}"
        path = self.home / "Library/LaunchAgents" / f"{label}.plist"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(plistlib.dumps({"Label": label, "ProgramArguments": [script or str(self.github / "agents" / RETIRE.JOBS[suffix]), "--apply"]}))
        return path

    def test_fixture_jobs_are_removed_without_launchctl_and_unknown_job_is_preserved(self) -> None:
        owned = [self.make_job(suffix) for suffix in RETIRE.JOBS]
        unknown = self.make_job("claude-session-archiver", "/somewhere/custom-archiver.py", "com.other")
        migration = self.retirement()
        with mock.patch.object(RETIRE.subprocess, "run") as process:
            migration.plan()
            migration.apply()
        process.assert_not_called()
        self.assertTrue(unknown.exists())
        for path in owned:
            self.assertFalse(path.exists())
        self.assertEqual(len(list(migration.backup_dir.rglob("*.plist"))), 3)

    def test_live_job_unload_failure_keeps_plist_and_backup(self) -> None:
        job = self.make_job("copilot-session-pruner")
        migration = self.retirement()
        migration.plan()
        with mock.patch.object(RETIRE.pwd, "getpwuid", return_value=SimpleNamespace(pw_dir=str(self.home))), mock.patch.object(RETIRE.sys, "platform", "darwin"), mock.patch.object(RETIRE.subprocess, "run", side_effect=[subprocess.CompletedProcess([], 0, "loaded", ""), subprocess.CompletedProcess([], 1, "", "failed")]) as process:
            with self.assertRaisesRegex(RuntimeError, "Cannot unload"):
                migration.apply()
        self.assertEqual(process.call_count, 2)
        self.assertTrue(job.exists())
        self.assertEqual(len(list(migration.backup_dir.rglob("*.plist"))), 1)

    def test_invalid_json_prevents_all_mutation_and_does_not_echo_contents(self) -> None:
        guidance = write_text(self.home / "bin/claude", '#!/usr/bin/env bash\nset -euo pipefail\nCLAUDE_REAL_BIN:-$default_real_cli\nclaude launcher cannot find executable real CLI:\nexec "$real_cli" --dangerously-skip-permissions "$@"\n')
        bad = write_text(self.home / ".copilot/settings.json", '{"token":"PRIVATE", broken}')
        result = self.run_retire("--apply", check=False)
        self.assertEqual(result.returncode, 2)
        self.assertNotIn("PRIVATE", result.stdout + result.stderr)
        self.assertTrue(guidance.exists())
        self.assertTrue(bad.exists())
        self.assertFalse((self.home / ".local/state").exists())

    def test_registers_only_repo_writes_and_preserves_raced_file(self) -> None:
        repo_file = write_text(self.repo / ".claude/CLAUDE.md", "@../AGENTS.md\n")
        write_json(self.home / ".copilot/settings.json", {"askUser": False})
        migration = self.retirement()
        migration.plan()
        with mock.patch.object(RETIRE, "register_current_codex_transaction_paths", return_value={}) as register:
            migration.apply()
        register.assert_called_once_with({repo_file})
        raced = write_text(self.repo / ".claude/CLAUDE.md", "@../AGENTS.md\n")
        migration = self.retirement()
        migration.plan()
        raced.write_text("new handwritten guidance\n")
        with self.assertRaisesRegex(RuntimeError, "File changed"):
            migration.apply()
        self.assertEqual(raced.read_text(), "new handwritten guidance\n")
