from __future__ import annotations

import shlex
import sys
import tomllib
from pathlib import Path

from tests.control_plane.support import (
    REPO_ROOT,
    TempDirTestCase,
    init_git_repo,
    run_command,
    write_json,
    write_text,
)


class CodexPreviewSyncTests(TempDirTestCase):
    def setUp(self) -> None:
        super().setUp()
        self.github_root = self.temp_path / "GitHub"
        self.registry = self.temp_path / "agents/dev-servers/registry.json"
        self.preview_runner = self.temp_path / "agents/scripts/run-agent-preview-server.py"

    def entry(self, repo: str = "repo-a", port: int = 3000, **server: object) -> dict[str, object]:
        return {
            "repo": repo,
            "servers": [
                {
                    "name": "Preview",
                    "host": "127.0.0.1",
                    "runtimeExecutable": "pnpm",
                    "runtimeArgs": ["dev", "--host", "{host}", "--port", "{port}"],
                    "port": port,
                    "autoPort": False,
                    **server,
                }
            ],
        }

    def write_registry(self, *entries: dict[str, object]) -> None:
        write_json(self.registry, {"version": 1, "managed_dev_servers": list(entries)})

    def run_sync(self, *args: str, check: bool = True):
        return run_command(
            [
                sys.executable,
                str(REPO_ROOT / "scripts/sync-codex-previews.py"),
                "--dev-servers-registry",
                str(self.registry),
                "--github-root",
                str(self.github_root),
                "--preview-runner",
                str(self.preview_runner),
                *args,
            ],
            check=check,
        )

    @staticmethod
    def target(repo: Path) -> Path:
        return repo / ".codex/environments/environment.toml"

    def test_apply_preserves_environment_format_and_fixed_port_command(self) -> None:
        repo = init_git_repo(self.github_root / "repo-a")
        self.write_registry(self.entry())

        self.run_sync("--apply", "--repo", str(repo))

        expected = (
            "# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY\n"
            "version = 1\n"
            'name = "repo-a"\n'
            "\n"
            "[setup]\n"
            'script = ""\n'
            "\n"
            "[[actions]]\n"
            'name = "Preview"\n'
            'icon = "run"\n'
            'command = "/bin/bash -lc \'python3 '
            f"{self.preview_runner.resolve()} --host 127.0.0.1 --port 3000 -- "
            'pnpm dev --host 127.0.0.1 --port 3000\'"\n'
        )
        self.assertEqual(expected, self.target(repo).read_text(encoding="utf-8"))
        self.assertEqual({".git", ".codex"}, {path.name for path in repo.iterdir()})

    def test_default_dry_run_check_apply_and_idempotent_check(self) -> None:
        repo = init_git_repo(self.github_root / "repo-a")
        self.write_registry(self.entry())

        dry_run = self.run_sync()
        self.assertIn("SYNC", dry_run.stdout)
        self.assertFalse(self.target(repo).exists())
        self.run_sync("--dry-run")
        self.assertFalse(self.target(repo).exists())

        missing = self.run_sync("--check", check=False)
        self.assertEqual(1, missing.returncode)
        self.assertIn("OUT OF SYNC", missing.stderr)
        self.assertFalse(self.target(repo).exists())

        self.run_sync("--apply")
        original = self.target(repo).read_bytes()
        modified = self.target(repo).stat().st_mtime_ns
        self.assertIn("in sync", self.run_sync("--check").stdout)
        self.assertIn("UNCHANGED", self.run_sync("--apply").stdout)
        self.assertEqual(modified, self.target(repo).stat().st_mtime_ns)
        self.assertEqual(original, self.target(repo).read_bytes())

        self.target(repo).write_text("stale config\n", encoding="utf-8")
        stale = self.run_sync("--check", check=False)
        self.assertEqual(1, stale.returncode)
        self.assertEqual("stale config\n", self.target(repo).read_text(encoding="utf-8"))

    def test_preview_environment_is_opt_in_per_repo(self) -> None:
        repo = init_git_repo(self.github_root / "repo-a")
        other = init_git_repo(self.github_root / "repo-b")
        custom = write_text(self.target(other), "# User-owned environment\n")
        self.write_registry(self.entry())

        self.run_sync("--apply")

        self.assertTrue(self.target(repo).is_file())
        self.assertEqual("# User-owned environment\n", custom.read_text(encoding="utf-8"))

    def test_repo_filter_is_exact_and_repeatable(self) -> None:
        repo_a = init_git_repo(self.github_root / "repo-a")
        repo_b = init_git_repo(self.github_root / "repo-a-other")
        repo_c = init_git_repo(self.github_root / "repo-c")
        self.write_registry(self.entry(), self.entry("repo-a-other", 3001), self.entry("repo-c", 3002))

        self.run_sync("--apply", "--repo", str(repo_a), "--repo", str(repo_c))

        self.assertTrue(self.target(repo_a).is_file())
        self.assertTrue(self.target(repo_c).is_file())
        self.assertFalse(self.target(repo_b).exists())
        self.run_sync("--check", "--repo", str(repo_a))

    def test_unregistered_checkout_with_same_name_is_not_selected(self) -> None:
        registered = init_git_repo(self.github_root / "repo-a")
        unrelated = init_git_repo(self.temp_path / "unrelated/repo-a")
        self.write_registry(self.entry())

        self.run_sync("--apply", "--repo", str(unrelated))

        self.assertFalse(self.target(registered).exists())
        self.assertFalse(self.target(unrelated).exists())

    def test_linked_worktree_uses_its_own_repo_root_and_keeps_shared_github_root(self) -> None:
        main = init_git_repo(self.github_root / "repo-a", with_initial_commit=True)
        worktree = self.temp_path / "worktrees/preview"
        run_command(["git", "-C", str(main), "worktree", "add", "-q", "-b", "preview", str(worktree)])
        self.write_registry(
            self.entry(
                runtimeExecutable="/bin/bash",
                runtimeArgs=[
                    "-lc",
                    "cd {repo_root}/dashboard && WORKSPACE={github_root}/person pnpm dev --host {host} --port {port}",
                ],
            )
        )

        self.run_sync("--apply", "--repo", str(worktree))

        self.assertFalse(self.target(main).exists())
        environment = tomllib.loads(self.target(worktree).read_text(encoding="utf-8"))
        self.assertEqual("repo-a", environment["name"])
        outer = shlex.split(environment["actions"][0]["command"])
        wrapped = shlex.split(outer[2])
        self.assertEqual(
            f"cd {worktree.resolve()}/dashboard && WORKSPACE={self.github_root.resolve()}/person pnpm dev --host 127.0.0.1 --port 3000",
            wrapped[-1],
        )
        self.run_sync("--check", "--repo", str(worktree))

    def test_home_paths_remain_portable_and_shell_arguments_round_trip(self) -> None:
        self.github_root = Path.home() / "GitHub"
        repo = init_git_repo(self.github_root / "repo-a")
        self.preview_runner = Path.home() / "GitHub/agents/scripts/run-agent-preview-server.py"
        argument = "a quote's value and a newline\nhere"
        self.write_registry(
            self.entry(runtimeExecutable="{repo_root}/bin/preview", runtimeArgs=[argument])
        )

        self.run_sync("--apply")

        environment = tomllib.loads(self.target(repo).read_text(encoding="utf-8"))
        command = environment["actions"][0]["command"]
        self.assertNotIn(str(Path.home()), command)
        outer = shlex.split(command)
        self.assertEqual(["/bin/bash", "-lc"], outer[:2])
        wrapped = shlex.split(outer[2])
        self.assertEqual("${HOME}/GitHub/agents/scripts/run-agent-preview-server.py", wrapped[1])
        self.assertEqual("${HOME}/GitHub/repo-a/bin/preview", wrapped[-2])
        self.assertEqual(argument, wrapped[-1])

    def test_absolute_registry_repo_and_home_expansion(self) -> None:
        repo = init_git_repo(Path.home() / "projects/repo-a")
        self.write_registry(self.entry("~/projects/repo-a"))
        self.run_sync("--apply", "--repo", "~/projects/repo-a")
        self.assertTrue(self.target(repo).is_file())

        other = init_git_repo(self.temp_path / "elsewhere/repo-b")
        self.write_registry(self.entry(str(other)))
        self.run_sync("--apply", "--repo", str(other))
        self.assertTrue(self.target(other).is_file())

    def test_missing_and_non_git_repos_are_not_created_or_modified(self) -> None:
        non_git = self.github_root / "non-git"
        non_git.mkdir(parents=True)
        self.write_registry(self.entry("absent"), self.entry("non-git", 3001))

        result = self.run_sync("--apply")

        self.assertIn("skipping existing non-git path", result.stderr)
        self.assertFalse((self.github_root / "absent").exists())
        self.assertEqual([], list(non_git.iterdir()))

    def test_subdirectory_filter_is_rejected_without_writing(self) -> None:
        repo = init_git_repo(self.github_root / "repo-a")
        nested = repo / "src"
        nested.mkdir()
        self.write_registry(self.entry())

        result = self.run_sync("--apply", "--repo", str(nested), check=False)

        self.assertEqual(2, result.returncode)
        self.assertIn("exact checkout root", result.stderr)
        self.assertFalse(self.target(repo).exists())

    def test_registry_validation_precedes_any_writes(self) -> None:
        repo = init_git_repo(self.github_root / "repo-a")
        valid_repo = init_git_repo(self.github_root / "valid-first")
        invalid_servers = [
            ([self.entry()["servers"][0], self.entry("other", 3001)["servers"][0]], "exactly one"),
            ([{**self.entry()["servers"][0], "autoPort": True}], "autoPort must be false"),
            ([{**self.entry()["servers"][0], "autoPort": "false"}], "autoPort must be a boolean"),
            ([{**self.entry()["servers"][0], "port": True}], "port must be an integer"),
            ([{**self.entry()["servers"][0], "port": 0}], "between 1 and 65535"),
            ([{**self.entry()["servers"][0], "port": 65536}], "between 1 and 65535"),
            ([{**self.entry()["servers"][0], "runtimeArgs": ["dev", "--port", "3000"]}], "hardcodes port 3000"),
            ([{**self.entry()["servers"][0], "runtimeArgs": [5]}], "array of strings"),
        ]
        for servers, message in invalid_servers:
            with self.subTest(message=message, servers=servers):
                self.write_registry(self.entry("valid-first", 3002), {"repo": "repo-a", "servers": servers})
                result = self.run_sync("--apply", check=False)
                self.assertEqual(2, result.returncode)
                self.assertIn(message, result.stderr)
                self.assertFalse(self.target(repo).exists())
                self.assertFalse(self.target(valid_repo).exists())

    def test_duplicate_repo_and_port_are_rejected(self) -> None:
        for entries, message in [
            ([self.entry(), self.entry("repo-a", 3001)], "duplicate dev-server repo entries"),
            ([self.entry(), self.entry("repo-b", 3000)], "port 3000 duplicates"),
        ]:
            with self.subTest(message=message):
                self.write_registry(*entries)
                result = self.run_sync("--apply", check=False)
                self.assertEqual(2, result.returncode)
                self.assertIn(message, result.stderr)

    def test_missing_or_invalid_registry_fails_and_modes_are_exclusive(self) -> None:
        missing = self.run_sync("--check", check=False)
        self.assertEqual(2, missing.returncode)
        self.assertIn("Codex preview sync failed", missing.stderr)
        for content in ["invalid JSON", "[]", '{"managed_dev_servers": {}}']:
            with self.subTest(content=content):
                write_text(self.registry, content)
                self.assertEqual(2, self.run_sync("--apply", check=False).returncode)
        self.write_registry()
        self.assertEqual(2, self.run_sync("--check", "--apply", check=False).returncode)
